source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Kawagarbo_iOS_Example' do
  pod 'Kawagarbo_iOS', :path => '../'

  target 'Kawagarbo_iOS_Tests' do
    inherit! :search_paths

    
  end
end
